Creating contract
 -> (Pair (Pair (Pair 200000000000000000000 (Pair 100000000000000000 "tz1R6Ej25VSerE3MkSoEEeBjKHCDTFbpKuSX")) (Pair "tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf" (Pair 1000000000000000000 "1601871456"))) (Pair (Pair 80000000000000000 (Pair "tz3QSGPoRp3Kn7n3vY24eYeu3Peuqo45LQ4D" "tz1c461F8GirBvq5DpFftPoPyCcPR7HQM6gm")) (Pair (Pair 20000000000000000000 0) (Pair "tz1W5VkdB5s7ENMESVBtwyt9kyvLqPcUczRT" "tz1cYufsxHXJcvANhvS55h3aY32a9BAFB494"))))
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_storage.tz 1
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_storage.json 37
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_sizes.csv 2
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_storage.py 1
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_types.py 7
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_contract.tz 4902
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_contract.json 4383
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_000_cont_0_contract.py 290
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_001_cont_0_params.py 1
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_001_cont_0_params.tz 1
 => ./smartpy_out/borrow_-_fails_when_not_called_by_ovenProxy/step_001_cont_0_params.json 37
Executing borrow((1000000000000000000, (sp.address('tz1LmaFsWRkjr7QMCx5PtV6xTUz3AmEpKQiF'), (sp.address('tz1S8MNvuFEUsWgjHvi3AxibRBf388NhT1q2'), (2 * 1000000000000000000, (0, (True, (0, (sp.to_int(1000000000000000000), 1000000000000000000)))))))))...
 -> --- Expected failure in transaction --- WrongCondition in line 89: sp.sender == self.data.ovenProxyContractAddress [2]
